spring:
  datasource: # 数据库连接配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 你的开发库地址
    url: jdbc:mysql://localhost:3306/codemate_backend_db_dev
    # 你的开发库用户名
    username: codemate_backend_db_dev
    # 你的开发库密码
    password: 112233665qw

  data:
    redis:
      host: localhost  # 告诉 Spring Boot：Redis 服务器就在本机
      port: 6379       # 告诉 Spring Boot：Redis 正 6379 端口上“监听”
      # (如果你的 Redis 设置了密码，才需要加这行)
      # password: your-password

  # 【【【 案卷 #12：Redisson 配置 】】】
  redisson:
    config: |
      singleServerConfig:
        address: "redis://localhost:6379"
        database: 0

  flyway: # Flyway 配置
    baseline-on-migrate: true # 允许在已有表上初始化
    configuration:
      map-underscore-to-camel-case: true # 确保这一行是 true

mybatis-plus:
  # 告诉 Mybatis-Plus 去哪里找 XML 文件
  # classpath: 指的是 src/main/resources/ 目录
  mapper-locations: classpath:mapper/*.xml

# 阿里云 OSS 配置 (已添加到 .gitignore)
aliyun:
  oss:
    # 你的 OSS Endpoint (外网)
    endpoint: oss-cn-beijing.aliyuncs.com
    # 你的 RAM 用户 AccessKey ID
    access-key-id: LTAI5tQSUBT7TBf2Em6jtWCA
    # 你的 RAM 用户 AccessKey Secret
    access-key-secret: P8xpOPCRMznPElFsUFYOmvrV8iyQae
    # 你的 Bucket 名称
    bucket-name: pingyu-storage

logging:
  level:
    # 1. 开启你自己的业务代码日志 (DEBUG 级别可以看到更多流程信息)
    com.pingyu.codematebackend: DEBUG
    # 2. 【核心】开启 MyBatis SQL 日志 (这是透视数据库交互的关键)
    # 这会把每一条发往数据库的 SQL 和参数都打印在控制台
    com.pingyu.codematebackend.mapper: DEBUG

# 在 application.yml (或 application-dev.yml) 中添加
