server:
  port: 8080 # 1. ????????????
  servlet:
    context-path: /api # 2. (?????): ?? API ?????

spring:
  application:
    name: codemate-backend # 3. (??): ?????????
  profiles:
    active: dev # 4. ???????????? (????? dev)

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 5. ?????????????
  # (????????????????? @TableLogic)